//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Dynamics.Web.Saplocalhost {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Saplocalhost.WebServiceConnectSAPSoap")]
    public interface WebServiceConnectSAPSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/connectSAPTEST", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SapValue[]))]
        bool connectSAPTEST(out string errStr, MCS.Dynamics.Web.Saplocalhost.SAPPara sappara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEntityDefine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SapValue[]))]
        System.Data.DataTable GetEntityDefine(string tCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteSAP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SapValue[]))]
        System.Data.DataTable ExecuteSAP(out string sapresult, string tCode, MCS.Dynamics.Web.Saplocalhost.InstanceParam param, MCS.Dynamics.Web.Saplocalhost.SAPPara sapPara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SAP_RFCParams_Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SapValue[]))]
        System.Data.DataTable SAP_RFCParams_Get(string RFCName, MCS.Dynamics.Web.Saplocalhost.SAPPara sappara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteSAPRFC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SapValue[]))]
        MCS.Dynamics.Web.Saplocalhost.InstanceParam ExecuteSAPRFC(string rfcFunctionName, MCS.Dynamics.Web.Saplocalhost.InstanceParam instanceParam, MCS.Dynamics.Web.Saplocalhost.SAPPara sapParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SAP_TableFiled_Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SapValue[]))]
        System.Data.DataTable SAP_TableFiled_Get(string TableName, MCS.Dynamics.Web.Saplocalhost.SAPPara sappara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadTableData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SapValue[]))]
        System.Data.DataTable ReadTableData(MCS.Dynamics.Web.Saplocalhost.ReadTableParam rtp, MCS.Dynamics.Web.Saplocalhost.SAPPara sappara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadTableAllDataSplit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SapValue[]))]
        System.Data.DataTable ReadTableAllDataSplit(out bool isEnd, string tableName, string[] fields, string whereClause, int rowSkip, MCS.Dynamics.Web.Saplocalhost.SAPPara sappara);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SAPPara : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string applicationServerField;
        
        private string appServerServiceField;
        
        private int systemNumberField;
        
        private string clientField;
        
        private string userField;
        
        private string passwordField;
        
        private string languageField;
        
        private string logonGroupField;
        
        private string messageServerHostField;
        
        private string messageServerServiceField;
        
        private string systemIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ApplicationServer {
            get {
                return this.applicationServerField;
            }
            set {
                this.applicationServerField = value;
                this.RaisePropertyChanged("ApplicationServer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AppServerService {
            get {
                return this.appServerServiceField;
            }
            set {
                this.appServerServiceField = value;
                this.RaisePropertyChanged("AppServerService");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SystemNumber {
            get {
                return this.systemNumberField;
            }
            set {
                this.systemNumberField = value;
                this.RaisePropertyChanged("SystemNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("Client");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LogonGroup {
            get {
                return this.logonGroupField;
            }
            set {
                this.logonGroupField = value;
                this.RaisePropertyChanged("LogonGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MessageServerHost {
            get {
                return this.messageServerHostField;
            }
            set {
                this.messageServerHostField = value;
                this.RaisePropertyChanged("MessageServerHost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MessageServerService {
            get {
                return this.messageServerServiceField;
            }
            set {
                this.messageServerServiceField = value;
                this.RaisePropertyChanged("MessageServerService");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SystemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
                this.RaisePropertyChanged("SystemID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadTableParam : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tableNameField;
        
        private int rowCountField;
        
        private string whereClauseField;
        
        private int rowSkipField;
        
        private int packageSizeField;
        
        private string[] fieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("TableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int RowCount {
            get {
                return this.rowCountField;
            }
            set {
                this.rowCountField = value;
                this.RaisePropertyChanged("RowCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string WhereClause {
            get {
                return this.whereClauseField;
            }
            set {
                this.whereClauseField = value;
                this.RaisePropertyChanged("WhereClause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int RowSkip {
            get {
                return this.rowSkipField;
            }
            set {
                this.rowSkipField = value;
                this.RaisePropertyChanged("RowSkip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PackageSize {
            get {
                return this.packageSizeField;
            }
            set {
                this.packageSizeField = value;
                this.RaisePropertyChanged("PackageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("Fields");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SapValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InstanceParam : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InType sapTypeField;
        
        private SapValue[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InType SapType {
            get {
                return this.sapTypeField;
            }
            set {
                this.sapTypeField = value;
                this.RaisePropertyChanged("SapType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public SapValue[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum InType {
        
        /// <remarks/>
        StandardInterface,
        
        /// <remarks/>
        CustomInterface,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceConnectSAPSoapChannel : MCS.Dynamics.Web.Saplocalhost.WebServiceConnectSAPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceConnectSAPSoapClient : System.ServiceModel.ClientBase<MCS.Dynamics.Web.Saplocalhost.WebServiceConnectSAPSoap>, MCS.Dynamics.Web.Saplocalhost.WebServiceConnectSAPSoap {
        
        public WebServiceConnectSAPSoapClient() {
        }
        
        public WebServiceConnectSAPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceConnectSAPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceConnectSAPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceConnectSAPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool connectSAPTEST(out string errStr, MCS.Dynamics.Web.Saplocalhost.SAPPara sappara) {
            return base.Channel.connectSAPTEST(out errStr, sappara);
        }
        
        public System.Data.DataTable GetEntityDefine(string tCode) {
            return base.Channel.GetEntityDefine(tCode);
        }
        
        public System.Data.DataTable ExecuteSAP(out string sapresult, string tCode, MCS.Dynamics.Web.Saplocalhost.InstanceParam param, MCS.Dynamics.Web.Saplocalhost.SAPPara sapPara) {
            return base.Channel.ExecuteSAP(out sapresult, tCode, param, sapPara);
        }
        
        public System.Data.DataTable SAP_RFCParams_Get(string RFCName, MCS.Dynamics.Web.Saplocalhost.SAPPara sappara) {
            return base.Channel.SAP_RFCParams_Get(RFCName, sappara);
        }
        
        public MCS.Dynamics.Web.Saplocalhost.InstanceParam ExecuteSAPRFC(string rfcFunctionName, MCS.Dynamics.Web.Saplocalhost.InstanceParam instanceParam, MCS.Dynamics.Web.Saplocalhost.SAPPara sapParam) {
            return base.Channel.ExecuteSAPRFC(rfcFunctionName, instanceParam, sapParam);
        }
        
        public System.Data.DataTable SAP_TableFiled_Get(string TableName, MCS.Dynamics.Web.Saplocalhost.SAPPara sappara) {
            return base.Channel.SAP_TableFiled_Get(TableName, sappara);
        }
        
        public System.Data.DataTable ReadTableData(MCS.Dynamics.Web.Saplocalhost.ReadTableParam rtp, MCS.Dynamics.Web.Saplocalhost.SAPPara sappara) {
            return base.Channel.ReadTableData(rtp, sappara);
        }
        
        public System.Data.DataTable ReadTableAllDataSplit(out bool isEnd, string tableName, string[] fields, string whereClause, int rowSkip, MCS.Dynamics.Web.Saplocalhost.SAPPara sappara) {
            return base.Channel.ReadTableAllDataSplit(out isEnd, tableName, fields, whereClause, rowSkip, sappara);
        }
    }
}
