//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCS.Library.Properties.ScriptResources", typeof(ScriptResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //注意，此客户端类的名称必须与服务端ClientValidateMethodName相同,默认为类名,且必须包含validate方法
        ///$HGRootNS.ValidatorManager.DateTimeEmptyValidator = function () {
        ///    this.validate = function (cvalue) {
        ///        var isValidate = false;
        ///        isValidate = (cvalue != &quot;&quot;);
        ///
        ///        if (isValidate)
        ///            isValidate = Date.isMinDate(cvalue) == false;
        ///        return isValidate;
        ///    }
        ///};
        ///.
        /// </summary>
        internal static string DatetimeEmptyValidator {
            get {
                return ResourceManager.GetString("DatetimeEmptyValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $HGRootNS.ValidatorManager.DateTimeRangeValidator = function () {
        ///    this.validate = function (cvalue, additionalData) {
        ///        var isValidate = false;
        ///        var sourcevalue = cvalue;
        ///        var lowerBound = additionalData.lowerBound;
        ///        var upperBound = additionalData.upperBound;
        ///
        ///        if (sourcevalue * 1 &lt; lowerBound * 1 || sourcevalue * 1 &gt; upperBound * 1) {
        ///            isValidate = false;
        ///        }
        ///        else {
        ///            isValidate = true;
        ///        }
        ///
        ///        return isValid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DateTimeRangeValidator {
            get {
                return ResourceManager.GetString("DateTimeRangeValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $HGRootNS.ValidatorManager.EnumDefaultValueValidator = function () {
        ///    this.validate = function (cvalue, additionalData) {
        ///        var isValidate = false;
        ///        if (cvalue) {
        ///            isValidate = cvalue != additionalData.tag;
        ///        }
        ///        return isValidate;
        ///    }
        ///};
        ///.
        /// </summary>
        internal static string EnumDefaultValueValidator {
            get {
                return ResourceManager.GetString("EnumDefaultValueValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $HGRootNS.ValidatorManager.IntegerRangeValidator = function () {
        ///    this.validate = function (cvalue, additionalData) {
        ///        var sourcevalue = cvalue;
        ///        var lowerBound = additionalData.lowerBound;
        ///        var upperBound = additionalData.upperBound;
        ///
        ///        sourcevalue = sourcevalue.toString().replace(/,/g, &apos;&apos;);
        ///
        ///        if (isNaN(sourcevalue * 1) == true) {
        ///            return false;
        ///        }
        ///        if (sourcevalue * 1 &lt; lowerBound * 1 || sourcevalue * 1 &gt; upperBound * 1) {
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IntegerRangeValidator {
            get {
                return ResourceManager.GetString("IntegerRangeValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $HGRootNS.ValidatorManager.NotNullValidator = function () {
        ///    this.validate = function (cvalue) {
        ///        var isValidate = false;
        ///        if (cvalue) {
        ///            isValidate = true;
        ///        }
        ///        return isValidate;
        ///    }
        ///};
        ///.
        /// </summary>
        internal static string NotNullValidator {
            get {
                return ResourceManager.GetString("NotNullValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $HGRootNS.ValidatorManager.ObjectNullValidator = function () {
        ///    this.validate = function (cvalue) {
        ///        var isValidate = false;
        ///        if (cvalue) {
        ///            isValidate = true;
        ///        }
        ///        return isValidate;
        ///    }
        ///};
        ///.
        /// </summary>
        internal static string ObjectNullValidator {
            get {
                return ResourceManager.GetString("ObjectNullValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $HGRootNS.ValidatorManager.RegexValidator = function () {
        ///    this.validate = function (cvalue, additionalData) {
        ///        if (additionalData.isNumber === true) {
        ///            cvalue = cvalue.toString().replace(/,/g, &apos;&apos;);
        ///        }
        ///
        ///        var isValidate = false;
        ///        var reg = new RegExp(additionalData.pattern);
        ///        isValidate = reg.test(cvalue);
        ///
        ///        return isValidate;
        ///    }
        ///};
        ///.
        /// </summary>
        internal static string RegexValidator {
            get {
                return ResourceManager.GetString("RegexValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $HGRootNS.ValidatorManager.StringEmptyValidator = function () {
        ///    this.validate = function (cvalue) {
        ///        var isValidate = false;
        ///        if (cvalue) {
        ///            isValidate = cvalue.length &gt; 0;
        ///        }
        ///        return isValidate;
        ///    }
        ///};
        ///.
        /// </summary>
        internal static string StringEmptyValidator {
            get {
                return ResourceManager.GetString("StringEmptyValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $HGRootNS.ValidatorManager.StringLengthValidator = function () {
        ///    this.validate = function (cvalue, additionalData) {
        ///        var sourcevalue = cvalue.length;
        ///        var lowerBound = additionalData.lowerBound;
        ///        var upperBound = additionalData.upperBound;
        ///
        ///        if (sourcevalue * 1 &lt; lowerBound * 1 || sourcevalue * 1 &gt; upperBound * 1) {
        ///            return false;
        ///        }
        ///        else {
        ///            return true;
        ///        }
        ///    }
        ///};
        ///.
        /// </summary>
        internal static string StringLengthValidator {
            get {
                return ResourceManager.GetString("StringLengthValidator", resourceCulture);
            }
        }
    }
}
