//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Dynamics.Web.SapUserCompare {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SapUserCompare.SapUserCompareServiceSoap")]
    public interface SapUserCompareServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadEntityPage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MCS.Dynamics.Web.SapUserCompare.TB_SapUserCompare[] LoadEntityPage(out int total, out string errorMessage, MCS.Dynamics.Web.SapUserCompare.SapUserCompareCustom info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadEntityPageBySapUserAndConnect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MCS.Dynamics.Web.SapUserCompare.TB_SapUserCompare[] LoadEntityPageBySapUserAndConnect(out int total, out string errorMessage, MCS.Dynamics.Web.SapUserCompare.SapUserCompareCustom info, MCS.Dynamics.Web.SapUserCompare.SapConnection con);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSapConnectionByUepId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MCS.Dynamics.Web.SapUserCompare.SapConnection GetSapConnectionByUepId(out string errorMessage, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSapConnectionByUepIdAndSqlCon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MCS.Dynamics.Web.SapUserCompare.SapConnection GetSapConnectionByUepIdAndSqlCon(out string errorMessage, string id, MCS.Dynamics.Web.SapUserCompare.SapConnection con);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SapUserCompareCustom : TB_SapUserCompare {
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        private string orderbyField;
        
        private bool isDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
                this.RaisePropertyChanged("PageIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("PageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Orderby {
            get {
                return this.orderbyField;
            }
            set {
                this.orderbyField = value;
                this.RaisePropertyChanged("Orderby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsDesc {
            get {
                return this.isDescField;
            }
            set {
                this.isDescField = value;
                this.RaisePropertyChanged("IsDesc");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SapUserCompareCustom))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TB_SapUserCompare : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid guidField;
        
        private string uepIdField;
        
        private string uepNameField;
        
        private string sapIdField;
        
        private string sapNameField;
        
        private string sapPassWordField;
        
        private string roleField;
        
        private string sapserversSystemField;
        
        private string sapserversApplicationserverField;
        
        private string sapserversSystemnumberField;
        
        private string sapserversClientField;
        
        private string sapserversUserField;
        
        private string sapserversPasswordField;
        
        private string sapserversLanguageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("Guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UepId {
            get {
                return this.uepIdField;
            }
            set {
                this.uepIdField = value;
                this.RaisePropertyChanged("UepId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UepName {
            get {
                return this.uepNameField;
            }
            set {
                this.uepNameField = value;
                this.RaisePropertyChanged("UepName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SapId {
            get {
                return this.sapIdField;
            }
            set {
                this.sapIdField = value;
                this.RaisePropertyChanged("SapId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SapName {
            get {
                return this.sapNameField;
            }
            set {
                this.sapNameField = value;
                this.RaisePropertyChanged("SapName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SapPassWord {
            get {
                return this.sapPassWordField;
            }
            set {
                this.sapPassWordField = value;
                this.RaisePropertyChanged("SapPassWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SapserversSystem {
            get {
                return this.sapserversSystemField;
            }
            set {
                this.sapserversSystemField = value;
                this.RaisePropertyChanged("SapserversSystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SapserversApplicationserver {
            get {
                return this.sapserversApplicationserverField;
            }
            set {
                this.sapserversApplicationserverField = value;
                this.RaisePropertyChanged("SapserversApplicationserver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SapserversSystemnumber {
            get {
                return this.sapserversSystemnumberField;
            }
            set {
                this.sapserversSystemnumberField = value;
                this.RaisePropertyChanged("SapserversSystemnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SapserversClient {
            get {
                return this.sapserversClientField;
            }
            set {
                this.sapserversClientField = value;
                this.RaisePropertyChanged("SapserversClient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SapserversUser {
            get {
                return this.sapserversUserField;
            }
            set {
                this.sapserversUserField = value;
                this.RaisePropertyChanged("SapserversUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SapserversPassword {
            get {
                return this.sapserversPasswordField;
            }
            set {
                this.sapserversPasswordField = value;
                this.RaisePropertyChanged("SapserversPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SapserversLanguage {
            get {
                return this.sapserversLanguageField;
            }
            set {
                this.sapserversLanguageField = value;
                this.RaisePropertyChanged("SapserversLanguage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SapConnection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string systemField;
        
        private string applicationServerField;
        
        private string systemNumberField;
        
        private string clientField;
        
        private string userField;
        
        private string passwordField;
        
        private string languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string System {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
                this.RaisePropertyChanged("System");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ApplicationServer {
            get {
                return this.applicationServerField;
            }
            set {
                this.applicationServerField = value;
                this.RaisePropertyChanged("ApplicationServer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SystemNumber {
            get {
                return this.systemNumberField;
            }
            set {
                this.systemNumberField = value;
                this.RaisePropertyChanged("SystemNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("Client");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SapUserCompareServiceSoapChannel : MCS.Dynamics.Web.SapUserCompare.SapUserCompareServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SapUserCompareServiceSoapClient : System.ServiceModel.ClientBase<MCS.Dynamics.Web.SapUserCompare.SapUserCompareServiceSoap>, MCS.Dynamics.Web.SapUserCompare.SapUserCompareServiceSoap {
        
        public SapUserCompareServiceSoapClient() {
        }
        
        public SapUserCompareServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SapUserCompareServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SapUserCompareServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SapUserCompareServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MCS.Dynamics.Web.SapUserCompare.TB_SapUserCompare[] LoadEntityPage(out int total, out string errorMessage, MCS.Dynamics.Web.SapUserCompare.SapUserCompareCustom info) {
            return base.Channel.LoadEntityPage(out total, out errorMessage, info);
        }
        
        public MCS.Dynamics.Web.SapUserCompare.TB_SapUserCompare[] LoadEntityPageBySapUserAndConnect(out int total, out string errorMessage, MCS.Dynamics.Web.SapUserCompare.SapUserCompareCustom info, MCS.Dynamics.Web.SapUserCompare.SapConnection con) {
            return base.Channel.LoadEntityPageBySapUserAndConnect(out total, out errorMessage, info, con);
        }
        
        public MCS.Dynamics.Web.SapUserCompare.SapConnection GetSapConnectionByUepId(out string errorMessage, string id) {
            return base.Channel.GetSapConnectionByUepId(out errorMessage, id);
        }
        
        public MCS.Dynamics.Web.SapUserCompare.SapConnection GetSapConnectionByUepIdAndSqlCon(out string errorMessage, string id, MCS.Dynamics.Web.SapUserCompare.SapConnection con) {
            return base.Channel.GetSapConnectionByUepIdAndSqlCon(out errorMessage, id, con);
        }
    }
}
